image: php:8.1

stages:
  - test

cache:
  key: $CI_COMMIT_SHA
  paths:
    - vendor/
    - tools/

composer:
  stage: test
  services: []
  before_script:
    - apt-get update
    - apt-get install zip unzip
    - docker-php-ext-install bcmath
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
  script:
    - php composer.phar install
    - php composer.phar install --working-dir=tools/php-cs-fixer/

pslam:
  stage: test
  services: []
  before_script: []
  script:
    - vendor/bin/psalm --version
    - vendor/bin/psalm --no-cache
  needs: ["composer"]

php-cs-fixer:
  stage: test
  services: []
  before_script: []
  allow_failure: true
  script:
    - PHP_CS_FIXER_IGNORE_ENV=true tools/php-cs-fixer/vendor/bin/php-cs-fixer --version
    - PHP_CS_FIXER_IGNORE_ENV=true tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --verbose --show-progress=dots --config=tools/php-cs-fixer/.php-cs-fixer.php --allow-risky=yes
  needs: ["composer"]