# https://taskfile.dev

version: '3'

vars:
  WAIT_COMMAND: bash -c 'while true; do echo Hit CTRL+C to stop test container; sleep 300; done'

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: Build the docker containers
    cmds:
      - docker build --ssh default -t app.churchillrecoverysolutions.co.uk:dev .

  composer:install:
    desc: Install packages for tools, app and tests
    cmds:
        - composer i --no-scripts
        - composer i --working-dir=./tools/php-cs-fixer/
        - composer i --working-dir=./tools/deptrac/

  composer:update:
    desc: Update app packages
    cmds:
      - composer update --no-scripts
      - composer update --working-dir=./tools/php-cs-fixer/
      - composer update --working-dir=./tools/deptrac/

  host:psalm:
    cmds:
      - ./vendor/bin/psalm --version
      - ./vendor/bin/psalm --no-cache

  host:php-cs-fixer:
    desc: Run php-cs-fixer
    cmds:
      - tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=tools/php-cs-fixer/.php-cs-fixer.php --allow-risky=yes {{.CLI_ARGS}}

  host:phpunit:
    cmds:
      - ./vendor/bin/phpunit tests/Unit

  host:deptrac:base:
    desc: Run deptrac
    cmds:
      - tools/deptrac/vendor/bin/deptrac analyse tools/deptrac/depfile.yaml --no-cache

  lint:
    desc: Run the linting
    cmds:
      - task: host:psalm
      - |
        export PHP_CS_FIXER_IGNORE_ENV=true && \
          ./tools/php-cs-fixer/vendor/bin/php-cs-fixer --version && \
          ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --verbose --show-progress=dots --config=tools/php-cs-fixer/.php-cs-fixer.php --allow-risky=yes

  lint:fix:
    desc: Fix any linting or code standards automatically
    cmds:
      - task: host:psalm
      - task: host:php-cs-fixer

  pipeline:
    desc: Run the pipeline
    cmds:
      - task: host:php-cs-fixer
      - task: host:psalm
      - task: host:phpunit